config = {
    'host': 'localhost',
    'database': lol
    'user': 'root',
    'password': 'root',
    'port': '3306' # change the port to match the port your SQL server is running on
}

Traceback (most recent call last):
  File "server.py", line 6, in <module>
    mysql = MySQLConnector(app, 'mydb')
  File "/Users/Snebaybay/Desktop/Assignments/New/flask_mysql/mysqlconnection.py", line 40, in MySQLConnector
    return MySQLConnection(app, db)
  File "/Users/Snebaybay/Desktop/Assignments/New/flask_mysql/mysqlconnection.py", line 9, in __init__
    'database': lol, # we got db as an argument
NameError: global name 'lol' is not defined
(venv) snehas-mbp:flask_mysql Snebaybay$ 

  config = {
    'host': 'localhost',
    'database': db
    'user': 'root',
    'password': 'bagel',
    'port': '3306' # change the port to match the port your SQL server is running on
}

  File "/Users/Snebaybay/Desktop/Assignments/New/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'rootabaga'@'localhost' (using password: YES)")
(venv) snehas-mbp:flask_mysql Snebaybay$ 


sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(venv) snehas-mbp:flask_mysql Snebaybay$ 